server:
  port: 8765

spring:
  application:
    name: alphanumeric-recognizer-admin
  profiles:
    active: dev
  boot:
    admin:
      discovery:
        ignored-services: alphanumeric-recognizer-discovery

eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF