version: '3'
services:
  discovery-service:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-discovery-server:1.0-SNAPSHOT
    ports:
      - 8761:8761
  admin-service:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-admin-service:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
    ports:
      - 8765:8765
  api-service:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-api-service:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
      - admin-service
    ports:
      - 8081:8081
  ml-agent:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-ml-agent:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
      - admin-service
    ports:
      - 8082:8082
  zuul-proxy:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-zuul-proxy:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
    ports:
      - 8762:8762
  ui-thymeleaf-app:
    image: com.jeremiahseagraves.ai.alphanumeric-recognizer-app-thymeleaf:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
      - admin-service
    ports:
      - 8080:8080
  ui-angular-app:
    container_name: alphanumericrecognizer-app-angular
    build:
      context: app-angular  # Location of our Dockerfile
      dockerfile: Dockerfile
    ports:
      - 4200:4200 # Port mapping
  mysql-alphanumeric-recognizer:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alphanumeric_recognizer
    ports:
      - "3308:3306"