version: '3'
services:
  discovery-service:
    image: com.jeremiahseagraves.ai-alphanumeric-recognizer-discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761
  admin-service:
    image: com.jeremiahseagraves.ai-alphanumeric-recognizer-admin:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
    ports:
      - 8765:8765
  api-service:
    image: com.jeremiahseagraves.ai-alphanumeric-recognizer-api:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
      - admin-service
    ports:
      - 8081:8081
  ui-thymeleaf-service:
    image: com.jeremiahseagraves.ai-alphanumeric-recognizer-ui-thymeleaf:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-service
      - admin-service
    ports:
      - 8083:8080
  ui-angular-service:
    hostname: localhost
    container_name: alphanumericrecognizer-ui-angular-service
    build: .
    ports:
      - 4200:4200