server:
  error:
    whitelabel:
      enabled: false
  port: 8081

spring:
  application:
    name: api-service
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

