server:
  error:
    whitelabel:
      enabled: false
  port: 8081

spring:
  application:
    name: aplhanumeric-recognizer-api-com.jeremiahseagraves.ai.service
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}