server:
  error:
    whitelabel:
      enabled: false
  port: 8762

spring:
  application:
    name: zuul-proxy
  profiles:
    active: dev


eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

