server:
  port: 8761

spring:
  application:
    name: discovery-server
  profiles:
    active: dev


eureka:
  client:
    register-with-eureka: false #not to register this service
    fetch-registry: false #should not fetch discovery information from the server
  server:
    response-cache-update-interval-ms: 1000
  instance:
    lease-renewal-interval-in-seconds: 5
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
