server:
  error:
    whitelabel:
      enabled: false
  port: 8083

spring:
  application:
    name: classification-logger
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

